# Primer paso: Tomar una imagen oficial de Node.js para comenzar 
FROM node:16

# Se creara un directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar los archivos package.json y package-lock.json
COPY package*.json ./

# Se instalara las dependencias de la app
RUN npm install

# Se metera todo el código de la app dentro del contenedor
COPY . .

# Se debe instalar MySQL Client para conectar la app con la base de datos
RUN apt-get update && apt-get install -y mysql-client

# Se abrira el puerto 3000 para que la app sea accesible
EXPOSE 3000

# Se va a configurar la conexión a MySQL
ENV MYSQL_HOST=mysql
ENV MYSQL_DATABASE=nombre_bd
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=contraseña

# Aqui iniciamos la aplicación de Node.js
CMD ["npm", "start"]

